//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_book.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_u { get; set; }
        public string u_login { get; set; }
        public string u_password { get; set; }
        public int id_ur { get; set; }
    
        public virtual u_roles u_roles { get; set; }
    }
}
